baseURL: https://kizilkayabayram.github.io/
languageCode: en-us
title: Personal Blog
theme: "PaperMod"
publishdir: docs


params:
  defaultTheme: auto 
  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - name: Search
      url: search/
      weight: 1
    - name: Archive
      url: archives/
      weight: 2
    - name: Categories
      url: categories/
      weight: 3
    - name: Tags
      url: tags/
      weight: 4

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
    style: monokai

